version: '3.7'
services:
  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   container_name: db_portfolio
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - mynetwork
  #   expose:
  #   - 5432
  # # This is for our database management   
  # pgadmin:
  #   image: "dpage/pgadmin4"
  #   restart: unless-stopped
  #   container_name: pgadmin_portfolio
  #   depends_on:
  #     - db
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #     - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
  #   ports: 
  #     - "5050:8001"
  #   networks:
  #     - mynetwork
  #web -> activate venv makemigrations migrate collectstatic then run apache2ctl
  inzynierka_backend:
    build: .
    command: bash -c "python3 /app/manage.py makemigrations
      && python3 /app/manage.py migrate
        && python3 /app/manage.py runserver 0:8000"
    restart: unless-stopped
    volumes:
      # copy our code to specific place to make changes in time 
      - ./mechanik:/app
    
    ports: 
      - "8000:8000"
    # for setting database: name, login, password 
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # depends_on:
    #   - db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
