# Generated by Django 4.1 on 2022-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_reservation_was_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_receive',
            field=models.DateTimeField(null=True),
        ),
    ]
