# Generated by Django 4.1 on 2022-11-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('date_visit', models.DateTimeField()),
                ('date_visit_end', models.DateTimeField(null=True)),
                ('date_created_visit', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car')),
                ('carplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.carplace')),
                ('visitdescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.visitdescription')),
                ('visitreason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.visitreason')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('progress', models.CharField(choices=[('T', 'Do zrobienia'), ('D', 'W trakcie'), ('DN', 'Zrobione')], max_length=20)),
                ('date_start', models.DateTimeField(null=True)),
                ('duration', models.SmallIntegerField(default=0)),
                ('date_end', models.DateTimeField(null=True)),
                ('servicename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.servicename')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartaken', models.BooleanField(default=False)),
                ('services', models.ManyToManyField(to='visit.service')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.visit')),
            ],
        ),
    ]
