# Generated by Django 4.1 on 2022-09-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Nr_VIN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('M', 'Mechanic'), ('C', 'Client')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('D', 'Damaged')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Category', to='kalendarz.category')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='mechanik/assets/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Offer_Item', serialize=False, to='kalendarz.item')),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='mechanik/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_Car', to='kalendarz.car')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Repair_Service', to='kalendarz.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Repair_Visit', to='kalendarz.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('about_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Client_About_Who', to='kalendarz.client')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Client_Author', to='kalendarz.client')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_Client', to='kalendarz.client'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_receive', models.DateTimeField()),
                ('was_taken', models.BooleanField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resevation_Cleint', to='kalendarz.client')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservation_Offer', to='kalendarz.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('number_of_stars', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opinion_Offer', to='kalendarz.offer')),
            ],
        ),
    ]
