# Generated by Django 4.1 on 2022-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
    ]
