# Generated by Django 4.1 on 2022-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0002_alter_news_image_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
