# Generated by Django 4.1 on 2022-10-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_created']},
        ),
    ]
