# Generated by Django 4.1 on 2022-11-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carbrand')),
                ('carmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_VIN', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='static/')),
                ('carbrandmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carbrandmodel')),
                ('cartype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cartype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.userinfo')),
            ],
        ),
    ]
